package Utils;

public enum MessageType{
	DEPLACER,
	ASSECHER,
	SPECIAL,
	PASSER,
        CHOISIR_DEPLACEMENT,
	CHOISIR_ASSECHEMENT,
        VALIDER_PARAMETRES,
	QUITTER,
        ANNULER_SELECTION;
}
